apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "7077"
      port: 7077
      targetPort: 7077
  type: LoadBalancer
  selector:
    io.kompose.service: spark-master
status:
  loadBalancer: {}