apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: spark-master
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spark-master
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.service: spark-master
    spec:
      containers:
        - name: spark-master
          image: spark:3.3
          ports:
            - containerPort: 8080
            - containerPort: 7077
          env:
            - name: SPARK_LOCAL_STORAGE_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_MODE
              value: master
            - name: SPARK_RPC_AUTHENTICATION_ENABLED
              value: "no"
            - name: SPARK_RPC_ENCRYPTION_ENABLED
              value: "no"
            - name: SPARK_SSL_ENABLED
              value: "no"
            # - name: DEPLOY_MODE
            #   value: "cluster"
          resources: {}
            # requests:
            #   cpu: 100m
            # limits:
            #   cpu: 100m
            #   memory: 2000Mi
          stdin: true
          tty: true
      hostname: spark-master
      restartPolicy: Always
status: {}

